# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rescue_pf?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  redis:
    #????
    timeout: 10000ms
    #??????????????????
    host: localhost
    #?????
    port: 6379
    #???
    database: 0
    #?????????????
    lettuce:
      pool:
        #????????8
        max-active: 1024
        #?????????????-1
        max-wait: 10000ms
        #??????
        max-idle: 200
        #??????
        min-idle: 5


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8081



# jwt??
jwt:
  # JWT??????
  # ?????? tokenHeader?Authorization ?key tokenHead?Bearer??? value ??????jwt?????????
  tokenHeader: Authorization
  # JWT ????????
  secret: yeb-secret
  # JWT???????60*60*24?
  expiration: 604800
  # JWT ???????
  tokenHead: Bearer

